---
name: Run Super-Linter
on:
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - '**.yml'
jobs:
  build:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Super-Linter against code base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}