name: 'Lint'
on:
  pull_request:
    paths:
      - '**.md'
      - '**.yml'
jobs:
  lint:
    name: 'Super-Linter v4.9.5'
    runs-on: ubuntu-latest
    steps:
      - name: 'Lint'
        uses: github/super-linter@v4.9.5
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
